title: Saurabh Rawat
author: Saurabh Rawat
email: saurabh.rawat90@gmail.com
description: "Saurabh Rawat's blog where he tries really hard to sound smart."
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Saurabh Rawat
  tagline: Developer. Enterpreneur
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  disqus_shortname: AVTHlKyoNi
  navigation:
    - title: Resume
      url: "/resume"
    - title: Categories
      url: /categories/
    - title: Tags
      url: /tags/

  # generate social links in footer
  social_links:
    github:  eklavya
    linkedIn: in/rawatsaurabh
    rss: rss
    # dribbble: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # facebook: jekyll
    # soundcloud: jekyll
    # telegram: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - resume.md

# Build settings
remote_theme: thelehhman/plainwhite-jekyll

plugins:
  - jekyll-seo-tag
#  - jekyll-feed

category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"
